# Generated by Django 4.2.3 on 2023-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_tg',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_id',
            field=models.IntegerField(unique=True),
        ),
    ]
