# Generated by Django 4.2.3 on 2023-08-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_fund', '0002_alter_group_group_tg_alter_profile_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
