# Generated by Django 4.2.3 on 2023-08-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_fund', '0003_alter_profile_tg_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_tg_id', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
