# Generated by Django 4.2.3 on 2023-08-31 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_fund', '0004_registeredgroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredGroups',
            new_name='RegisteredGroup',
        ),
    ]
